name: myoptional

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake ..
      env:
        CXX: g++
        CC: gcc

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make -j3

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure

  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake ..

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make -j4

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure

  Windows:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake .. -G "Visual Studio 16 2019" -A x64

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config Release -- /m

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release --output-on-failure
